services:
  backend:
    environment:
      PORT: "80"
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "app"
      BACKEND_KEY: "banana"
    env_file:
      - ./.env.ci
    depends_on:
      - database
  # frontend:
  #   image: node:24.9.0-slim
  #   working_dir: /app
  #   command: sh -c "yarn install && yarn dev"
  #   ports:
  #     - "8080:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #     - API_SERVICE=http://backend:80/api/
  #     - NEXTAUTH_URL=http://localhost:8080
  #   depends_on:
  #     - backend
  database:
    image: debezium/postgres:17
    ports:
      - 19235:5432
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    volumes:
      - ./build/postgres-data:/var/lib/postgresql/data
